Document: wcm
Title: Debian wcm Manual
Author: <insert document author here>
Abstract: This manual describes what wcm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wcm/wcm.sgml.gz

Format: postscript
Files: /usr/share/doc/wcm/wcm.ps.gz

Format: text
Files: /usr/share/doc/wcm/wcm.text.gz

Format: HTML
Index: /usr/share/doc/wcm/html/index.html
Files: /usr/share/doc/wcm/html/*.html
