# Find libsmbclient
#
# SMBCLIENT_INCLUDE_DIR
# SMBCLIENT_LIBRARY
# SMBCLIENT_FOUND
#

FIND_PATH(SMBCLIENT_INCLUDE_DIR NAMES libsmbclient.h PATH_SUFFIXES samba-4.0)

FIND_LIBRARY(SMBCLIENT_LIBRARY NAMES smbclient)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SMBCLIENT DEFAULT_MSG SMBCLIENT_LIBRARY SMBCLIENT_INCLUDE_DIR)

MARK_AS_ADVANCED(SMBCLIENT_INCLUDE_DIR SMBCLIENT_LIBRARY)
