# Find libssh2
#
# SSH2_INCLUDE_DIR
# SSH2_LIBRARY
# SSH2_FOUND
#

FIND_PATH(SSH2_INCLUDE_DIR NAMES libssh2.h)

FIND_LIBRARY(SSH2_LIBRARY NAMES ssh2)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SSH2 DEFAULT_MSG SSH2_LIBRARY SSH2_INCLUDE_DIR)

MARK_AS_ADVANCED(SSH2_INCLUDE_DIR SSH2_LIBRARY)
